AracIhaleDemo01/Models/Entities/Arac.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AracIhaleDemo01.Models.Entities
{
    public class Arac:Base
    {
        [Key]
        public int AracID { get; set; }
        public KayitTip KayitTip { get; set; }
        public int KayitTipID { get; set; }
        public string SirketAdi { get; set; }
        public AracStatu AracStatu { get; set; }
        public int AracStatuID { get; set; }
        public int AracFiyat { get; set; }
        public string KMBilgisi { get; set; }
        public string Donanim { get; set; }
        public string Resim1 { get; set; }
        public string Resim2 { get; set; }
        public string Resim3 { get; set; }
        public string Resim4 { get; set; }
        public string Resim5 { get; set; }
        public string Aciklama { get; set; }
        public int MarkaId { get; set; }
        public int YilId { get; set; }
        public int ModelId { get; set; }
        public int GovdeTipi { get; set; }
        public int YakitTipi { get; set; }
        public int VitesTipi { get; set; }
        public int Versiyon { get; set; }
        public int RenkId { get; set; }

    }
}

AracIhaleDemo01/Controllers/AracController.cs
using AracIhaleDemo01.Models.Entities;
using AracIhaleDemo01.Models.DTOs;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AracIhaleDemo01.Controllers
{
    public class AracController : Controller
    {
        private readonly AracIhaleDemo01Entities context;

        public AracController(AracIhaleDemo01Entities _context)
        {
            context = _context;
        }

        public IActionResult AracEkle()
        {
            //var result = (from a in context.Arac
            //              select new AracEkleDTO
            //              {

            //              });
            return View();
        }
        [HttpGet]
        public IActionResult AracList()
        {
            var status = (from a in context.AracStatu
                          where a.IsActive == 1
                          select new AracStatuDTO
                          {
                              AracStatuID = a.AracStatuID,
                              AracStatuAdi = a.AracStatuAdi
                          }).ToList();

            var models = (from a in context.AracDetay
                          where a.IsActive == 1 && a.GrupAdi == "Model"
                          select new AracModelDTO
                          {
                              AracModelID = a.AracDetayID,
                              AracModelAdi = a.Value
                          }).ToList();

            var markas = (from a in context.AracDetay
                          where a.IsActive == 1 && a.GrupAdi == "Marka"
                          select new AracMarkaDTO
                          {
                              AracMarkaID = a.AracDetayID,
                              AracMarkaAdi = a.Value
                          }).ToList();

            ViewBag.AracMarkalari = new SelectList(markas, "AracMarkaID", "AracMarkaAdi");
            ViewBag.AracModelleri = new SelectList(models, "AracModelID", "AracModelAdi");
            ViewBag.AracStatuleri = new SelectList(status, "AracStatuID", "AracStatuAdi");

            if (TempData["aracList"] != null)
            {
                var serilizeData = TempData["aracList"].ToString();
                List<AracDTO> aracList = JsonSerializer.Deserialize<List<AracDTO>>(serilizeData);
                ViewBag.aracList = aracList;
                TempData["aracList"] = null;
            }
            return View();
        }

        [HttpPost]
        public IActionResult AracListPost(int aracMarkaId, int aracModelId, int aracStatuId)
        {
            List<AracDTO> aracList = (from a in context.Arac
                        join ad in context.AracDetay on a.MarkaId equals ad.AracDetayID
                        join k in context.Kullanici on a.CreatedBy equals k.KullaniciID
                        join s in context.AracStatu on a.AracStatuID equals s.AracStatuID
                        join x in context.AracDetay on a.ModelId equals x.AracDetayID
                        where a.IsActive == 1
                        select new AracDTO
                        {
                            AracID = a.AracID,
                            AracMarka = ad.Value,
                            AracMarkaID=a.MarkaId,
                            KaydedenKullaniciID = k.KullaniciID,
                            KaydedenKullanici = k.KullaniciAdi,
                            KaydetmeZamani = a.CreatedDate,
                            Statu = s.AracStatuAdi,
                            AracStatuID=a.AracStatuID,
                            AracModel = x.Value,
                            AracModelID=a.ModelId
                        }).ToList();

            if (aracMarkaId != 0)
            {
                aracList = aracList.Where(a => a.AracMarkaID == aracMarkaId).ToList();
            }
            if (aracStatuId != 0)
            {
                aracList = aracList.Where(a => a.AracStatuID == aracStatuId).ToList();
            }
            if (aracModelId != 0)
            {
                aracList = aracList.Where(a => a.AracModelID == aracModelId).ToList();
            }

            string serilizeData = JsonSerializer.Serialize(aracList);

            TempData["aracList"] = serilizeData;

            return RedirectToAction("aracList");
        }




    }
}

AracIhaleDemo01/Views/Arac/AracList.cshtml
@using AracIhaleDemo01.Models.DTOs
@model AracDTO

<form asp-action="AracListPost" asp-controller="Arac" method="post">

    <label asp-for="AracMarkaID" class="control-label"></label>
    <select id="MarkaList" asp-for="AracMarkaID" class="form-control" asp-items="@ViewBag.AracMarkalari">
        <option>Lütfen marka seçiniz...</option>
    </select>

    <label asp-for="AracModelID" class="control-label"></label>
    <select id="ModelList" asp-for="AracModelID" class="form-control" asp-items="@ViewBag.AracModelleri">
        <option>Lütfen model seçiniz...</option>
    </select>

    <label asp-for="AracStatuID" class="control-label"></label>
    <select id="StatuList" asp-for="AracStatuID" class="form-control" asp-items="@ViewBag.AracStatuleri">
        <option>Lütfen statü seçiniz...</option>
    </select>
    <br />
    <input id="submitButton" type="submit" value="Listele" style="margin-top:10px;" />
    <br />
</form>

@section Scripts
{
    <script>
        $("#submitButton").on('click', function () {
            var marka = $("#MarkaList").val();
            var model = $("#ModelList").val();
            var statu = $("#StatuList").val();
            debugger
            $.getJSON("/Arac/AracListPost?aracMarkaId=" + marka + "&aracModelId=" + model + "&aracStatuId=" + statu, function (data) {
                console.log(data);
            });
        });
    </script>
}

@if (ViewBag.aracList != null)
{
    <div style="margin-top:20px;">
        <table>
            <thead>
                <tr>
                    <th>Araç Marka</th>
                    <th>Araç Model</th>
                    <th>Statü</th>
                    <th>Kaydeden Kullanıcı</th>
                    <th>Kaydetme Zamanı</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.aracList)
                {
                <tr>
                    <td>@item.AracMarka</td>
                    <td>@item.AracModel</td>
                    <td>@item.Statu</td>
                    <td>@item.KaydedenKullanici</td>
                    <td>@item.KaydetmeZamani</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
}

AracIhaleDemo01/Views/Arac/Index.cshtml
@{
}